# Generated by Django 5.2.15 on 2026-06-28 20:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_time', models.FloatField()),
                ('python_time', models.FloatField()),
                ('db_time', models.FloatField()),
                ('total_queries', models.IntegerField()),
                ('path', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField(null=True)),
                ('content_type', models.CharField(max_length=100, null=True)),
                ('body', models.TextField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('response_content', models.TextField(null=True)),
                ('response_status_code', models.IntegerField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('proxy_verified', models.BooleanField(null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditor',
                'verbose_name_plural': 'Auditor',
            },
        ),
    ]
