# Generated by Django 5.2.15 on 2026-07-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_backfill_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.CharField(choices=[('technology', 'Tecnologia'), ('education', 'Educação'), ('healthcare', 'Saúde'), ('retail', 'Varejo / Comércio'), ('manufacturing', 'Indústria'), ('services', 'Serviços'), ('construction', 'Construção civil'), ('public_sector', 'Órgão público'), ('other', 'Outro')], default='other', max_length=30, verbose_name='Setor de atuação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_goal',
            field=models.CharField(choices=[('it_equipment', 'Equipamentos de TI'), ('fixed_assets', 'Patrimônio / ativos fixos'), ('tools', 'Ferramentas'), ('internal_loans', 'Empréstimos internos'), ('maintenance', 'Manutenção de equipamentos'), ('other', 'Outro')], default='1-10', max_length=30, verbose_name='Principal uso pretendido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='size',
            field=models.CharField(choices=[('1-10', '1 a 10 pessoas'), ('11-50', '11 a 50 pessoas'), ('51-200', '51 a 200 pessoas'), ('200+', 'Mais de 200 pessoas')], default='other', max_length=10, verbose_name='Porte da equipe'),
            preserve_default=False,
        ),
    ]
