# Generated by Django 5.2.15 on 2026-07-18 15:01

from django.db import migrations, models


def backfill_member_role_to_operator(apps, schema_editor):
    """O papel genérico 'member' deixou de existir — quem tinha esse papel vira
    'operator' (pode cadastrar itens, mas não gerencia membros nem organização)."""
    Membership = apps.get_model("organizations", "Membership")
    Membership.objects.filter(role="member").update(role="operator")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_invitation'),
    ]

    operations = [
        migrations.RunPython(backfill_member_role_to_operator, noop),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('manager', 'Gerente'), ('operator', 'Operador'), ('viewer', 'Visualizador')], default='owner', max_length=20, verbose_name='Papel'),
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
