# Generated by Django 5.2.15 on 2026-07-27 18:37

import apps.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_membership_role_delete_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.organizations.models.organization_logo_upload_path, verbose_name='Logo'),
        ),
    ]
