# Generated by Django 5.2.15 on 2026-07-02 23:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_id', models.CharField(default='free', max_length=30, verbose_name='Plano')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('past_due', 'Pagamento pendente'), ('canceled', 'Cancelada')], default='active', max_length=20, verbose_name='Status')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Fim do período atual')),
                ('mp_preapproval_id', models.CharField(blank=True, max_length=100, verbose_name='ID da assinatura no Mercado Pago')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization', verbose_name='Organização')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
    ]
