from typing import Dict, List

DEVELOPMENT_REGIONS = [
    {"acronym": "RMR", "name": "Região Metropolitana do Recife"},
    {"acronym": "MN","name": "Mata Norte"},
    {"acronym": "MS","name": "Mata Sul"},
    {"acronym": "AS","name": "Agreste Setentrional"},
    {"acronym": "AC","name": "Agreste Central"},
    {"acronym": "AM", "name": "Agreste Meridional"},
    {"acronym": "SPJ", "name": "Sertão do Pajeú"},
    {"acronym": "SMX", "name": "Sertão do Moxotó"},
    {"acronym": "SC", "name": "Sertão Central"},
    {"acronym": "SA", "name": "Sertão do Araripe"},
    {"acronym": "SIT", "name": "Sertão de Itaparica"},
    {"acronym": "SSF", "name": "Sertão do São Francisco"},
]


IBGE_MUNICIPALITY: List[Dict[str, str]] = [
  {"name": "Abreu e Lima", "ibge_code": "2600054", "development_region": "RMR"},
  {"name": "Afogados da Ingazeira", "ibge_code": "2600104", "development_region": "SPJ"},
  {"name": "Afrânio", "ibge_code": "2600203", "development_region": "SSF"},
  {"name": "Agrestina", "ibge_code": "2600302", "development_region": "AC"},
  {"name": "Água Preta", "ibge_code": "2600401", "development_region": "MS"},
  {"name": "Águas Belas", "ibge_code": "2600500", "development_region": "AM"},
  {"name": "Alagoinha", "ibge_code": "2600609", "development_region": "AC"},
  {"name": "Aliança", "ibge_code": "2600708", "development_region": "MN"},
  {"name": "Altinho", "ibge_code": "2600807", "development_region": "AC"},
  {"name": "Amaraji", "ibge_code": "2600906", "development_region": "MS"},
  {"name": "Angelim", "ibge_code": "2601003", "development_region": "AM"},
  {"name": "Araçoiaba", "ibge_code": "2601052", "development_region": "RMR"},
  {"name": "Araripina", "ibge_code": "2601102", "development_region": "SA"},
  {"name": "Arcoverde", "ibge_code": "2601201", "development_region": "SMX"},
  {"name": "Barra de Guabiraba", "ibge_code": "2601300", "development_region": "AC"},
  {"name": "Barreiros", "ibge_code": "2601409", "development_region": "MS"},
  {"name": "Belém de Maria", "ibge_code": "2601508", "development_region": "MS"},
  {"name": "Belém do São Francisco", "ibge_code": "2601607", "development_region": "SIT"},
  {"name": "Belo Jardim", "ibge_code": "2601706", "development_region": "AC"},
  {"name": "Betânia", "ibge_code": "2601805", "development_region": "SMX"},
  {"name": "Bezerros", "ibge_code": "2601904", "development_region": "AC"},
  {"name": "Bodocó", "ibge_code": "2602001", "development_region": "SA"},
  {"name": "Bom Conselho", "ibge_code": "2602100", "development_region": "AM"},
  {"name": "Bom Jardim", "ibge_code": "2602209", "development_region": "AS"},
  {"name": "Bonito", "ibge_code": "2602308", "development_region": "AC"},
  {"name": "Brejão", "ibge_code": "2602407", "development_region": "AM"},
  {"name": "Brejinho", "ibge_code": "2602506", "development_region": "SPJ"},
  {"name": "Brejo da Madre de Deus", "ibge_code": "2602605", "development_region": "AC"},
  {"name": "Buenos Aires", "ibge_code": "2602704", "development_region": "MN"},
  {"name": "Buíque", "ibge_code": "2602803", "development_region": "SMX"},
  {"name": "Cabo de Santo Agostinho", "ibge_code": "2602902", "development_region": "RMR"},
  {"name": "Cabrobó", "ibge_code": "2603009", "development_region": "SSF"},
  {"name": "Cachoeirinha", "ibge_code": "2603108", "development_region": "AC"},
  {"name": "Caetés", "ibge_code": "2603207", "development_region": "AM"},
  {"name": "Calçado", "ibge_code": "2603306", "development_region": "AM"},
  {"name": "Calumbi", "ibge_code": "2603405", "development_region": "SPJ"},
  {"name": "Camaragibe", "ibge_code": "2603454", "development_region": "RMR"},
  {"name": "Camocim de São Félix", "ibge_code": "2603504", "development_region": "AC"},
  {"name": "Camutanga", "ibge_code": "2603603", "development_region": "MN"},
  {"name": "Canhotinho", "ibge_code": "2603702", "development_region": "AM"},
  {"name": "Capoeiras", "ibge_code": "2603801", "development_region": "AM"},
  {"name": "Carnaíba", "ibge_code": "2603900", "development_region": "SPJ"},
  {"name": "Carnaubeira da Penha", "ibge_code": "2603926", "development_region": "SIT"},
  {"name": "Carpina", "ibge_code": "2604007", "development_region": "MN"},
  {"name": "Caruaru", "ibge_code": "2604106", "development_region": "AC"},
  {"name": "Casinhas", "ibge_code": "2604155", "development_region": "AS"},
  {"name": "Catende", "ibge_code": "2604205", "development_region": "MS"},
  {"name": "Cedro", "ibge_code": "2604304", "development_region": "SC"},
  {"name": "Chã de Alegria", "ibge_code": "2604403", "development_region": "MN"},
  {"name": "Chã Grande", "ibge_code": "2604502", "development_region": "MS"},
  {"name": "Condado", "ibge_code": "2604601", "development_region": "MN"},
  {"name": "Correntes", "ibge_code": "2604700", "development_region": "AM"},
  {"name": "Cortês", "ibge_code": "2604809", "development_region": "MS"},
  {"name": "Cumaru", "ibge_code": "2604908", "development_region": "AS"},
  {"name": "Cupira", "ibge_code": "2605004", "development_region": "AC"},
  {"name": "Custódia", "ibge_code": "2605103", "development_region": "SMX"},
  {"name": "Dormentes", "ibge_code": "2605152", "development_region": "SSF"},
  {"name": "Escada", "ibge_code": "2605202", "development_region": "MS"},
  {"name": "Exu", "ibge_code": "2605301", "development_region": "SA"},
  {"name": "Feira Nova", "ibge_code": "2605400", "development_region": "MN"},
  {"name": "Fernando de Noronha", "ibge_code": "2605459", "development_region": "RMR"},
  {"name": "Ferreiros", "ibge_code": "2605509", "development_region": "MN"},
  {"name": "Flores", "ibge_code": "2605608", "development_region": "SPJ"},
  {"name": "Floresta", "ibge_code": "2605707", "development_region": "SIT"},
  {"name": "Frei Miguelinho", "ibge_code": "2605806", "development_region": "AS"},
  {"name": "Gameleira", "ibge_code": "2605905", "development_region": "MS"},
  {"name": "Garanhuns", "ibge_code": "2606002", "development_region": "AM"},
  {"name": "Glória do Goitá", "ibge_code": "2606101", "development_region": "MN"},
  {"name": "Goiana", "ibge_code": "2606200", "development_region": "MN"},
  {"name": "Granito", "ibge_code": "2606309", "development_region": "SA"},
  {"name": "Gravatá", "ibge_code": "2606408", "development_region": "AC"},
  {"name": "Iati", "ibge_code": "2606507", "development_region": "AM"},
  {"name": "Ibimirim", "ibge_code": "2606606", "development_region": "SMX"},
  {"name": "Ibirajuba", "ibge_code": "2606705", "development_region": "AC"},
  {"name": "Igarassu", "ibge_code": "2606804", "development_region": "RMR"},
  {"name": "Iguaracy", "ibge_code": "2606903", "development_region": "SPJ"},
  {"name": "Ilha de Itamaracá", "ibge_code": "2607604", "development_region": "RMR"},
  {"name": "Inajá", "ibge_code": "2607000", "development_region": "SMX"},
  {"name": "Ingazeira", "ibge_code": "2607109", "development_region": "SPJ"},
  {"name": "Ipojuca", "ibge_code": "2607208", "development_region": "RMR"},
  {"name": "Ipubi", "ibge_code": "2607307", "development_region": "SA"},
  {"name": "Itacuruba", "ibge_code": "2607406", "development_region": "SIT"},
  {"name": "Itaíba", "ibge_code": "2607505", "development_region": "AM"},
  {"name": "Itambé", "ibge_code": "2607653", "development_region": "MN"},
  {"name": "Itapetim", "ibge_code": "2607703", "development_region": "SPJ"},
  {"name": "Itapissuma", "ibge_code": "2607752", "development_region": "RMR"},
  {"name": "Itaquitinga", "ibge_code": "2607802", "development_region": "MN"},
  {"name": "Jaboatão dos Guararapes", "ibge_code": "2607901", "development_region": "RMR"},
  {"name": "Jaqueira", "ibge_code": "2607950", "development_region": "MS"},
  {"name": "Jataúba", "ibge_code": "2608008", "development_region": "AC"},
  {"name": "Jatobá", "ibge_code": "2608057", "development_region": "SIT"},
  {"name": "João Alfredo", "ibge_code": "2608107", "development_region": "AS"},
  {"name": "Joaquim Nabuco", "ibge_code": "2608206", "development_region": "MS"},
  {"name": "Jucati", "ibge_code": "2608255", "development_region": "AM"},
  {"name": "Jupi", "ibge_code": "2608305", "development_region": "AM"},
  {"name": "Jurema", "ibge_code": "2608404", "development_region": "AM"},
  {"name": "Lagoa de Itaenga", "ibge_code": "2608503", "development_region": "MN"},
  {"name": "Lagoa do Carro", "ibge_code": "2608453", "development_region": "MN"},
  {"name": "Lagoa do Ouro", "ibge_code": "2608602", "development_region": "AM"},
  {"name": "Lagoa dos Gatos", "ibge_code": "2608701", "development_region": "AC"},
  {"name": "Lagoa Grande", "ibge_code": "2608750", "development_region": "SSF"},
  {"name": "Lajedo", "ibge_code": "2608800", "development_region": "AM"},
  {"name": "Limoeiro", "ibge_code": "2608909", "development_region": "AS"},
  {"name": "Macaparana", "ibge_code": "2609006", "development_region": "MN"},
  {"name": "Machados", "ibge_code": "2609105", "development_region": "AS"},
  {"name": "Manari", "ibge_code": "2609154", "development_region": "SMX"},
  {"name": "Maraial", "ibge_code": "2609204", "development_region": "MS"},
  {"name": "Mirandiba", "ibge_code": "2609303", "development_region": "SC"},
  {"name": "Moreilândia", "ibge_code": "2614303", "development_region": "SA"},
  {"name": "Moreno", "ibge_code": "2609402", "development_region": "RMR"},
  {"name": "Nazaré da Mata", "ibge_code": "2609501", "development_region": "MN"},
  {"name": "Olinda", "ibge_code": "2609600", "development_region": "RMR"},
  {"name": "Orobó", "ibge_code": "2609709", "development_region": "AS"},
  {"name": "Orocó", "ibge_code": "2609808", "development_region": "SSF"},
  {"name": "Ouricuri", "ibge_code": "2609907", "development_region": "SA"},
  {"name": "Palmares", "ibge_code": "2610004", "development_region": "MS"},
  {"name": "Palmeirina", "ibge_code": "2610103", "development_region": "AM"},
  {"name": "Panelas", "ibge_code": "2610202", "development_region": "AC"},
  {"name": "Paranatama", "ibge_code": "2610301", "development_region": "AM"},
  {"name": "Parnamirim", "ibge_code": "2610400", "development_region": "SC"},
  {"name": "Passira", "ibge_code": "2610509", "development_region": "AS"},
  {"name": "Paudalho", "ibge_code": "2610608", "development_region": "MN"},
  {"name": "Paulista", "ibge_code": "2610707", "development_region": "RMR"},
  {"name": "Pedra", "ibge_code": "2610806", "development_region": "SMX"},
  {"name": "Pesqueira", "ibge_code": "2610905", "development_region": "AC"},
  {"name": "Petrolândia", "ibge_code": "2611002", "development_region": "SIT"},
  {"name": "Petrolina", "ibge_code": "2611101", "development_region": "SSF"},
  {"name": "Poção", "ibge_code": "2611200", "development_region": "AC"},
  {"name": "Pombos", "ibge_code": "2611309", "development_region": "MS"},
  {"name": "Primavera", "ibge_code": "2611408", "development_region": "MS"},
  {"name": "Quipapá", "ibge_code": "2611507", "development_region": "MS"},
  {"name": "Quixaba", "ibge_code": "2611533", "development_region": "SPJ"},
  {"name": "Recife", "ibge_code": "2611606", "development_region": "RMR"},
  {"name": "Riacho das Almas", "ibge_code": "2611705", "development_region": "AC"},
  {"name": "Ribeirão", "ibge_code": "2611804", "development_region": "MS"},
  {"name": "Rio Formoso", "ibge_code": "2611903", "development_region": "MS"},
  {"name": "Sairé", "ibge_code": "2612000", "development_region": "AC"},
  {"name": "Salgadinho", "ibge_code": "2612109", "development_region": "AS"},
  {"name": "Salgueiro", "ibge_code": "2612208", "development_region": "SC"},
  {"name": "Saloá", "ibge_code": "2612307", "development_region": "AM"},
  {"name": "Sanharó", "ibge_code": "2612406", "development_region": "AC"},
  {"name": "Santa Cruz", "ibge_code": "2612455", "development_region": "SA"},
  {"name": "Santa Cruz da Baixa Verde", "ibge_code": "2612471", "development_region": "SPJ"},
  {"name": "Santa Cruz do Capibaribe", "ibge_code": "2612505", "development_region": "AS"},
  {"name": "Santa Filomena", "ibge_code": "2612554", "development_region": "SA"},
  {"name": "Santa Maria da Boa Vista", "ibge_code": "2612604", "development_region": "SSF"},
  {"name": "Santa Maria do Cambucá", "ibge_code": "2612703", "development_region": "AS"},
  {"name": "Santa Terezinha", "ibge_code": "2612802", "development_region": "SPJ"},
  {"name": "São Benedito do Sul", "ibge_code": "2612901", "development_region": "MS"},
  {"name": "São Bento do Una", "ibge_code": "2613008", "development_region": "AC"},
  {"name": "São Caitano", "ibge_code": "2613107", "development_region": "AC"},
  {"name": "São João", "ibge_code": "2613206", "development_region": "AM"},
  {"name": "São Joaquim do Monte", "ibge_code": "2613305", "development_region": "AC"},
  {"name": "São José da Coroa Grande", "ibge_code": "2613404", "development_region": "MS"},
  {"name": "São José do Belmonte", "ibge_code": "2613503", "development_region": "SC"},
  {"name": "São José do Egito", "ibge_code": "2613602", "development_region": "SPJ"},
  {"name": "São Lourenço da Mata", "ibge_code": "2613701", "development_region": "RMR"},
  {"name": "São Vicente Férrer", "ibge_code": "2613800", "development_region": "MN"},
  {"name": "Serra Talhada", "ibge_code": "2613909", "development_region": "SPJ"},
  {"name": "Serrita", "ibge_code": "2614006", "development_region": "SC"},
  {"name": "Sertânia", "ibge_code": "2614105", "development_region": "SMX"},
  {"name": "Sirinhaém", "ibge_code": "2614204", "development_region": "MS"},
  {"name": "Solidão", "ibge_code": "2614402", "development_region": "SPJ"},
  {"name": "Surubim", "ibge_code": "2614501", "development_region": "AS"},
  {"name": "Tabira", "ibge_code": "2614600", "development_region": "SPJ"},
  {"name": "Tacaimbó", "ibge_code": "2614709", "development_region": "AC"},
  {"name": "Tacaratu", "ibge_code": "2614808", "development_region": "SIT"},
  {"name": "Tamandaré", "ibge_code": "2614857", "development_region": "MS"},
  {"name": "Taquaritinga do Norte", "ibge_code": "2615003", "development_region": "AS"},
  {"name": "Terezinha", "ibge_code": "2615102", "development_region": "AM"},
  {"name": "Terra Nova", "ibge_code": "2615201", "development_region": "SC"},
  {"name": "Timbaúba", "ibge_code": "2615300", "development_region": "MN"},
  {"name": "Toritama", "ibge_code": "2615409", "development_region": "AS"},
  {"name": "Tracunhaém", "ibge_code": "2615508", "development_region": "MN"},
  {"name": "Trindade", "ibge_code": "2615607", "development_region": "SA"},
  {"name": "Triunfo", "ibge_code": "2615706", "development_region": "SPJ"},
  {"name": "Tupanatinga", "ibge_code": "2615805", "development_region": "AM"},
  {"name": "Tuparetama", "ibge_code": "2615904", "development_region": "SPJ"},
  {"name": "Venturosa", "ibge_code": "2616001", "development_region": "SMX"},
  {"name": "Verdejante", "ibge_code": "2616100", "development_region": "SC"},
  {"name": "Vertente do Lério", "ibge_code": "2616183", "development_region": "AS"},
  {"name": "Vertentes", "ibge_code": "2616209", "development_region": "AS"},
  {"name": "Vicência", "ibge_code":"2616308", "development_region": "MN"},
  {"name": "Vitória de Santo Antão", "ibge_code": "2616407", "development_region": "MS"},
  {"name": "Xexéu", "ibge_code": "2616506", "development_region": "MS"}
]
