# Generated by Django 5.2.15 on 2026-07-26 03:21

import apps.settings.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Quando desativado, o sistema usa as variáveis de ambiente do servidor.', verbose_name='Usar configuração personalizada')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='Servidor SMTP')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='Porta')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('host_user', models.CharField(blank=True, max_length=255, verbose_name='Usuário SMTP')),
                ('host_password', apps.settings.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Senha SMTP')),
                ('default_from_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail remetente padrão')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de E-mail',
                'verbose_name_plural': 'Configurações de E-mail',
            },
        ),
    ]
