# Generated by Django 5.2.15 on 2026-07-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Enquanto desativado, o envio de e-mails do sistema fica bloqueado.', verbose_name='Ativar servidor SMTP'),
        ),
    ]
