# Generated by Django 5.2.15 on 2026-06-28 19:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setor',
            new_name='Sector',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['sector', 'name'], 'verbose_name': 'Localização', 'verbose_name_plural': 'Localizações'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='setor',
            new_name='sector',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='setor',
            new_name='sector',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='from_setor',
            new_name='from_sector',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='to_setor',
            new_name='to_sector',
        ),
    ]
