# Generated by Django 5.2.15 on 2026-07-02 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_brand_itemspec_brand_fk'),
        ('organizations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='organization',
            field=models.ForeignKey(default='11111111-1111-1111-1111-111111111111', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organizations.organization', verbose_name='Organização'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Código / Patrimônio'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_item_code_per_organization'),
        ),
    ]
