# Generated by Django 5.2.15 on 2026-07-15 01:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_organization_alter_item_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'Bem', 'verbose_name_plural': 'Bens'},
        ),
        migrations.AddField(
            model_name='item',
            name='ownership',
            field=models.CharField(choices=[('proprio', 'Próprio'), ('terceiros', 'Terceiros')], default='proprio', max_length=20, verbose_name='Titularidade'),
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.item')),
                ('cartorio_situacao', models.CharField(choices=[('registrado', 'Registrado'), ('nao_registrado', 'Não registrado'), ('em_registro', 'Em processo de registro')], default='nao_registrado', max_length=20, verbose_name='Situação em Cartório')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('zone', models.CharField(blank=True, choices=[('urbana', 'Urbana'), ('rural', 'Rural')], max_length=10, verbose_name='Zona')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Área total (m²)')),
                ('built_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Área construída (m²)')),
            ],
            options={
                'verbose_name': 'Bem Imóvel',
                'verbose_name_plural': 'Bens Imóveis',
                'ordering': ['name'],
            },
            bases=('inventory.item',),
        ),
        migrations.CreateModel(
            name='ImovelCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='inventory.imovelcategory', verbose_name='Categoria pai')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de Imóvel',
                'verbose_name_plural': 'Categorias de Imóvel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movel',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.item')),
                ('status', models.CharField(choices=[('em_uso', 'Em uso'), ('guardado', 'Guardado'), ('em_manutencao', 'Em manutenção'), ('descartado', 'Descartado'), ('extraviado', 'Extraviado')], default='em_uso', max_length=20, verbose_name='Situação Patrimonial')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category', verbose_name='Categoria')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.location', verbose_name='Localização')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.sector', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Bem Móvel',
                'verbose_name_plural': 'Bens Móveis',
                'ordering': ['name'],
            },
            bases=('inventory.item',),
        ),
        migrations.CreateModel(
            name='MovelSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(blank=True, max_length=150, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=150, verbose_name='Número de série')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/items/', verbose_name='Imagem')),
                ('extra_attributes', models.JSONField(blank=True, default=dict, verbose_name='Atributos extras')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_specs', to='inventory.brand', verbose_name='Marca')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('movel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='inventory.movel', verbose_name='Bem Móvel')),
            ],
            options={
                'verbose_name': 'Especificação do Bem Móvel',
                'verbose_name_plural': 'Especificações dos Bens Móveis',
            },
        ),
        migrations.DeleteModel(
            name='ItemSpec',
        ),
        migrations.AddField(
            model_name='imovel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imoveis', to='inventory.imovelcategory', verbose_name='Categoria'),
        ),
    ]
