# Generated by Django 5.2.15 on 2026-08-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_item_category_remove_item_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='warranty_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Alerta de garantia enviado em'),
        ),
        migrations.AddField(
            model_name='category',
            name='useful_life_months',
            field=models.PositiveIntegerField(blank=True, help_text='Usado para calcular a depreciação linear dos bens desta categoria. Deixe em branco para não depreciar.', null=True, verbose_name='Vida útil (meses)'),
        ),
    ]
