# Generated by Django 5.2.15 on 2026-09-07 04:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_acquisition_warranty_alert_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovelSpec',
            new_name='AssetSpec',
        ),
        migrations.RenameModel(
            old_name='Movel',
            new_name='MovableAsset',
        ),
        migrations.RenameModel(
            old_name='Imovel',
            new_name='RealEstateAsset',
        ),
        migrations.RenameModel(
            old_name='ImovelCategory',
            new_name='RealEstateCategory',
        ),
    ]
