# Generated by Django 5.2.15 on 2026-09-07 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_movelspec_assetspec_rename_movel_movableasset_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetspec',
            old_name='movel',
            new_name='asset',
        ),
        migrations.AlterField(
            model_name='movableasset',
            name='item_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='movable_asset', serialize=False, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='realestateasset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_assets', to='inventory.realestatecategory', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='realestateasset',
            name='item_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='real_estate_asset', serialize=False, to='inventory.item'),
        ),
    ]
